import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "직업 초성 게임",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
                {children}
<footer style={{ 
  textAlign: 'center', 
  padding: '16px', 
  fontSize: '14px', 
  color: 'rgba(255,255,255,0.7)', 
  width: '100%', 
  fontWeight: '500',
  background: 'transparent'
}}>
  © 2026 교육 콘텐츠 전문기업 (주)삼양문화. All rights reserved.
</footer>
      </body>
    </html>
  );
}
